apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pgadmin-configmap
  namespace: dev
  labels:
    name: {{ .Release.Name }}-pgadmin-configmap
    tier: weba
data:
  PGADMIN_DEFAULT_EMAIL: admin
  PGADMIN_DEFAULT_PASSWORD: admin